name: gds

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "info.yaml"

jobs:
  harden:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Run TinyTapeout OpenLane flow (Sky130)
      - name: Harden design to GDS
        uses: TinyTapeout/tt-gds-action@v1
        with:
          top_module: tt_um_counter

      # Upload results so other jobs (and you) can fetch them
      - name: Upload OpenLane artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tt-openlane-artifacts
          path: runs/**/results/**

  gls:
    needs: harden
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Get the post-layout netlist from the previous job
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: tt-openlane-artifacts
          path: artifacts

      # Find the gate-level netlist and drop it where test/Makefile expects it
      - name: Place gate_level_netlist.v
        run: |
          GL=$(find artifacts -name "tt_um_counter.gl.v" -print -quit)
          if [ -z "$GL" ]; then
            echo "ERROR: gate-level netlist not found in artifacts"
            exit 1
          fi
          cp "$GL" test/gate_level_netlist.v

      # Run GLS with cocotb using your existing test/Makefile
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog python3 python3-pip
          pip3 install -r test/requirements.txt
      - name: Gate-level sim (functional)
        working-directory: test
        env:
          GATES: "yes"
        run: make
