name: gds

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "info.yaml"
      - ".github/workflows/gds.yml"

jobs:
  gds:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Preflight: show repo layout
        run: |
          echo "PWD=$(pwd)"
          echo "=== ls root ==="; ls -la
          echo "=== info.yaml ==="; sed -n '1,200p' info.yaml || true
          echo "=== ls src ==="; ls -la src || true
          echo "=== grep top ==="; grep -R --line-number "module tt_um_counter" src || true
          echo "=== git ls-files ==="; git ls-files -- src/counter.v || true

      - name: Build GDS
        uses: TinyTapeout/tt-gds-action@ttsky25b
        with:
          pdk: sky130A

  precheck:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: Run Tiny Tapeout Precheck
        uses: TinyTapeout/tt-gds-action/precheck@ttsky25b

  gl_test:
    needs: gds
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: GL test
        uses: TinyTapeout/tt-gds-action/gl_test@ttsky25b

  viewer:
    needs: gds
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: TinyTapeout/tt-gds-action/viewer@ttsky25b
